import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget } from "@/components/PopupWidget";
import Banner from "@/components/Banner";
import Banner2 from "@/components/Banner2";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Torch Initiative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          
          
          <div>{children}</div>

          <PopupWidget />
        </ThemeProvider>
      </body>
    </html>
  );
}
